---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: xayma-azure-disk
provisioner: disk.csi.azure.com
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
reclaimPolicy: Delete # Default
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
