apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    tier: xayma_rdbms
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    tier: xayma_rdbms

---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    tier: xayma_rdbms
spec:
  serviceName: xayma-rdbms-mariadb
  replicas: 1
  selector:
    matchLabels:
      tier: xayma_rdbms
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Delete
  template:
    metadata:
      labels:
        tier: xayma_rdbms
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.0-rc
          resources:
            requests:
              cpu: 0.07
              memory: "256Mi"
            limits:
              cpu: 0.1
              memory: "512Mi"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          envFrom:
            - configMapRef:
                name: app-config
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: xayma-azure-disk
