apiVersion: v1
kind: Service
metadata:
  name: postgres-deployment-service
  labels:
    app: odoo
    tier: backend
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: odoo
    tier: backend

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-dev
  labels:
    app: odoo
    tier: backend
spec:
  storageClassName: default # Azure AKS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odoo
    tier: backend
  name: postgres13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
      tier: backend
  template:
    metadata:
      labels:
        app: odoo
        tier: backend
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: postgres
        image: postgres:13.0
        resources:
          requests:
            cpu: 0.07
            memory: "512Mi"
          limits:
            cpu: 0.1
            memory: "768Mi"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-database
        envFrom:
        - configMapRef:
            name: app-config
      volumes:
        - name: postgres-database
          persistentVolumeClaim:
            claimName: postgres-pvc-dev