apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-df
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
  storageAccount: t4daks1storage
  shareName: delice-food-erp
  secretNamespace: delice-food
  secretName: azure-storage-account-secret
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl