apiVersion: apps/v1
kind: Deployment
metadata:
  name: xaymalabs-mongodb-deployment
  labels:
    app: xaymalabs-mongodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xaymalabs-mongodb-app
  template:
    metadata:
      labels:
        app: xaymalabs-mongodb-app
    spec:
      containers:
      - name: xaymalabs-mongodb-pod
        image: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME 
            valueFrom:
              secretKeyRef:
                name: xaymalabs-mongo-secret
                key: mongo-username
          - name: MONGO_INITDB_ROOT_PASSWORD  
            valueFrom:
              secretKeyRef:
                name: xaymalabs-mongo-secret
                key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: xaymalabs-mongodb-service
spec:
  selector:
    app: xaymalabs-mongodb-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017