apiVersion: apps/v1
kind: Deployment
metadata:
  name: xaymalabs-mongoexpress-deployment
  labels:
    app: xaymalabs-mongoexpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xaymalabs-mongoexpress-app
  template:
    metadata:
      labels:
        app: xaymalabs-mongoexpress-app
    spec:
      containers:
      - name: xaymalabs-mongoexpress-pod
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
          valueFrom:
            secretKeyRef:
              name: xaymalabs-mongoexpress-secret
              key: mongo-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD  
          valueFrom:
            secretKeyRef:
              name: xaymalabs-mongoexpress-secret
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER  
          valueFrom:
            configMapKeyRef:
              name: xaymalabs-mongoexpress-deployment
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: xaymalabs-mongoexpress-service
spec:
  selector:
    app: xaymalabs-mongoexpress-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000