apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-df
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
  storageAccount: t4daks1storage
  shareName: delice-food-share
  secretNamespace: delice-food
  secretName: azure-storage-account-secret
mountOptions:
  - dir_mode=0750
  - file_mode=0750
  - uid=999
  - gid=999
  - mfsymlinks
  - nobrl