sudo: required
language: python
services:
  - docker

group: trusty_latest

env:
  global:
    - REGISTRY_USER=rapidproautomation
    - IMAGE="praekeltfoundation/courier" VERSION="" REPO="nyaruka/courier"
    - secure: TBwtks2Y5e4dSbV6FTnA5T3I178CC13K8mxmI2qk+eQ5kYRHOp4EqWVZF/jypPIoAy/YbO0CMB4Lhz3hDfilDE7pku6egGQT/mCT2UBCUGs+emIIWymBAbcx9uYnjwSRld5mrZ9lO59URNK6LIZd03IWi+urScRSI1k29qhN1PASZuUgXVpTNAVZNykXdM2MK6HxmyqRMpASMHhPATQnOvAspPRUgCkhxE5sG2Dr2baMqvR+019Wemj8JdZIIauNcgGEyCVXoDC9TAG0/abKxYpZvWJZ5UBboi3TMWgnKdlgBgdukh/pxWrtXxNKD6KpKR6oUuqqX7drbM78n4L74j4ytOFIv+JUEYTJb+mbSwGLaTdX2lnlop6y8E4FFjPp1JKtN43SdRS7XGB45MJoiyzeYFUPzdCED+p4rQQ4IKwxnF5IKYx5C/WXfY6bqaQR7PDaij8KbKSdD3R42NYjLdEFi1S5aLHvJVkmFQy/uxjpZ/Q2u4wgusOlixkBicAXHm3EuG61dhR0QuLUOEdwtR/thxWJxyK89T//8zWPyyrZv2WTDMOEXnAp8Av7Og4Cf816W6vjGE6GOfV/iWbeQ7L7jy9PvoDnaLiiDJEKhfUhOO+jrOqPyzhgkcfRXROe+y5CPAU5XvaQYaT5lsQtcRT9YX2PKkUuiER5phRm8DI=
    - secure: LBHg19eidUOEeGuKkAI0Hyn65ARmo5Y/6pSoq40FEpaDczbil8fEXwqq4e4QvGcCteKe+qik3yP9g+4gbCgFksdanhrcOx09Gsj+mHNLZKywEaOpB6T8HVXjBjTnRsgDiBHlrRKKn7W5gMSX0WieVhuguaHgH0svUkRDxxBSA//D1gy7Sv5FBWS48foMux4Jm9WbSbHKnG72DZkMzYZNctqqcdErt5tUDx0izoQ3GmmRNanLAp1+g//guerDHioE3XGsWsZu/ECnaVEf000UhH3zmA+Mv7HFGJVbRqAlUo2RBTpgKO4N/RHyVVYPfrb6Q2eimOtFhzg7dRuJKZsL0jJ02uDSDV1LOjaHLAAQsWBSm+0W7qE961wDpStn0LxBcw9BX5l7cNbBQsNKjfJ45tTYC1tjNjeAcNeLHRykO9AhrMlF+Nt2+Va+NNbAQlnn6swLeDBaS9Ui4+IopZEu+Ak1keIE7xQJH0sse3FjNGKZA6VY5ZcyC0VkrpfP7WaC7JT63abbAQWSVHrdkVIoGZ7daEOx/yxfSzJ6ealwVlIV2g2y5hixP7jTieEaUrQhtkp3I33QLcemzkwolbkumIFVwk+XLys2dDRJJ9qp9d0vaUcC7LrNupuB1dIG9JwSKIcBxc1rPxXjEueoH2fPzai5VNIjbbH7cARzEDppO8I=

before_script:
  - 'curl -H "Authorization: Bearer $GITHUB_ACCESS_TOKEN" -s https://api.github.com/repos/$REPO/tags | tee ./tags.json'
  - LATEST_TAG=$(cat ./tags.json | jq -r '.[0].name')
  - LATEST_TAG="${LATEST_TAG//[v]}"
  - VERSION=${VERSION:-$LATEST_TAG}

install: []

script:
  - docker pull "$IMAGE" || true
  - >
    docker build --pull --cache-from "$IMAGE" \
      --tag "$IMAGE" \
      --build-arg COURIER_VERSION=$VERSION \
      --build-arg COURIER_REPO=$REPO \
      .

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin

deploy:
  provider: script
  skip_cleanup: true
  script: dcd --tag-version "$VERSION" --tag-semver --tag-latest "$IMAGE"
  on:
    branch: master
